title: Make A Change
description: "You cannot weave a silk cloth from a cotton yarn"
keywords: "blog, web, programming, python, Rajesh Kumar Srivastav, Rajesh, Kumar, Srivastav, rks, rksriv"
author: "Rajesh Kumar Srivastav"
url: 'http://makeachange.co.in'
baseurl: '/'

# Outputting
permalink: pretty
paginate: 10
paginate_path: "/:num/"

# Plugins
gems: [jekyll-paginate]

# Conversion
highlighter: pygments

# Owner Info
author:
  name: 'Rajesh Kumar Srivastav'
  email: rks_201159@yahoo.co.in
  twitter_username: srivastav_rk
  #github_username: rksriv
  linkedin_username: rk-srivastav-995b8516
   
# Google Analytics 
google_analytics: UA-72846931-1

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
